### PR TITLE
Stronger password hashing

### PR DESCRIPTION
**Pull request by gmcharlt**
Submitting this for feedback. This works for me in initial testing, but some things to check include:

- making sure this doesn't break things for Shibboleth users
- making the update happen in the canonical style. Note that if an SP installation has a _lot_ of staff users (i.e., thousands), the bcrypt hashing could take a while.

### CODE REVIEW

**Comment by gmcharlt** [comment]
By the way, apologies if the specific patches are effectively noise due to the SP5 rewrite.

**Comment by agdarby** [comment]
Thanks, Galen.  Definitely not noise, we appreciate you working on this.  SP5 has been a bit delayed for various reasons, so this is great.

**Comment by cgb37** [comment]
Hi Galen, thanks so much for your help. I'm curious in your interest in SubjectsPlus. Are you installing an instance for a particular university? Also, I understand your concern for doing work that will be undertaken during the development of version 5. Would you be interested in working with us in the development process? We are thinking of using Symfony and adopting an API first approach using the Strangler Pattern. I would love to hear your thoughts on SubjectsPlus and how we can make it better.

**Comment by gmcharlt** [comment]
I work for a nonprofit that supplies various services for Koha and Evergreen. We're currently using SubjectsPlus to display some of our training and support resources, but we're also looking into offering services for SubjectsPlus as well to our clients.

Some of my short-terms goals (in addition to simply becoming more familiar with SubjectsPlus in general) include

- improving the upgrade process
- ironing out installation glitches
- enhancing integrations with Koha and Evergreen
- (maybe) creating Debian packages

I'd be happy to help out where I can with SP5.

**Comment by sandbergja** [comment]
Hi @gmcharlt!  Good to see you here!

I wanted to drop a note to say that  I:

* applied your commit in our development environment and ran `rehash_passwords.php`, and everything worked as expected.
* I did the same in our production environment, and it's been running smoothly for the past week.

Note that we aren't using shibboleth or anything, just the typical subjectsplus authentication.  We have 10 SubjectsPlus users, so the script took hardly any time at all.

**Comment by cgb37** [comment]
@sandbergja did you write a file called rehash_passwords.php?

**Comment by sandbergja** [comment]
@cgb37: sorry, I should have been more clear.  That file is in @gmcharlt's pull request, see here: https://github.com/gmcharlt/SubjectsPlus/blob/stronger-password-hashing/rehash_passwords.php

**Comment by cgb37** [comment]
@sandbergja excellent, thanks! i see that now. We're trying to clean up all the pull requests so that we can officially begin working on SP5

**Pull request merged**
